### TEST REST API
### Menggunakan Ekstensi VS Code REST Client
### BLOG API

GET http://localhost:3200/api/v1/blog/blog-list

###

GET http://localhost:3200/api/v1/blog/blogs/5f51e864215c4e12e307579c

###
### Kirim Data testing untuk cek validasi blog
POST http://localhost:3200/api/v1/blog/create-blog
Content-Type: application/x-www-form-urlencoded

title=b&snippet=ss&text=Isi

### Kirim Data script injection untuk cek validasi dan sanitize blog
POST http://localhost:3200/api/v1/blog/create-blog
Content-Type: application/x-www-form-urlencoded

title=Tes XSS Script Injection&snippet=<tr>
  <td>Hi, I'm your first cell.</td>
  <td>I'm your second cell.</td>
  <td>I'm your third cell.</td>
  <td>I'm your fourth cell.</td>
</tr>&text=<script>Person.prototype.greeting = function() {
  alert('Hi! I\'m ' + this.name.first + '.');
};</script>

# {
#     "title": "Judul blog",
#     "snippet": "Snippet singkat blog",
#     "text": "Isi panjang dari blog"
# }

###
DELETE  http://localhost:3200/api/v1/blog/blogs/5f3e4b0d7968394344eb9493
